__class__: smplfusion.models.unet.UNetModel
__init__:
  use_checkpoint: False
  use_fp16: True
  image_size: 32 # unused
  in_channels: 4
  out_channels: 4
  model_channels: 320
  attention_resolutions: [ 4, 2, 1 ]
  num_res_blocks: 2
  channel_mult: [ 1, 2, 4, 4 ]
  num_head_channels: 64
  use_spatial_transformer: True
  use_linear_in_transformer: True
  transformer_depth: 1
  context_dim: 1024
  legacy: False