parameterization: "v"
low_scale_key: "lr"
linear_start: 0.0001
linear_end: 0.02
num_timesteps_cond: 1
log_every_t: 200
timesteps: 1000
first_stage_key: "jpg"
cond_stage_key: "txt"
image_size: 128
channels: 4
cond_stage_trainable: false
conditioning_key: "hybrid-adm"
monitor: val/loss_simple_ema
scale_factor: 0.08333
use_ema: False

low_scale_config:
  target: ldm.modules.diffusionmodules.upscaling.ImageConcatWithNoiseAugmentation
  params:
    noise_schedule_config: # image space
      linear_start: 0.0001
      linear_end: 0.02
    max_noise_level: 350
